export const stageConfig: Record<string, { label: string; color: string }> = {
    templating: { label: 'Templating', color: 'text-blue-700' },
    pre_draft_review: { label: 'Pre-Draft Review', color: 'text-indigo-700' },
    drafting: { label: 'Drafting', color: 'text-green-700' },
    sales_ct: { label: 'Sales CT', color: 'text-yellow-700' },
    slab_smith_request: { label: 'SlabSmith Request', color: 'text-red-700' },
    slabsmith: { label: 'SlabSmith Request', color: 'text-red-700' },
    cut_list: { label: 'Cut List', color: 'text-purple-700' },
    final_programming: { label: 'Final Programming', color: 'text-orange-700' },
    revisions: { label: 'Revisions', color: 'text-purple-700' },
    draft: { label: 'Draft', color: 'text-green-700' },
    install_schedulling: { label: 'Install Scheduling', color: 'text-teal-700' },
    install_completion: { label: 'Install Completion', color: 'text-cyan-700' },
    shop_status: { label: 'Shop Status', color: 'text-blue-700' },
    shop: { label: 'Shop', color: 'text-indigo-700' },
    general: { label: 'General', color: 'text-gray-700' },
};
